import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { inflateSync } from 'node:zlib';

/**
 * The launcher icons are generated by tools/build-icons.mjs and committed. These
 * tests check the committed files still satisfy the constraints Android and the
 * Play Console impose, so a change to the logo geometry cannot quietly ship a
 * clipped or mis-sized icon.
 */

/** Minimal reader for the RGBA, non-interlaced PNGs the generator emits. */
function readPng(path) {
  const data = readFileSync(path);
  let offset = 8;
  let width = 0;
  let height = 0;
  const idat = [];
  while (offset < data.length) {
    const length = data.readUInt32BE(offset);
    const type = data.toString('latin1', offset + 4, offset + 8);
    const body = data.subarray(offset + 8, offset + 8 + length);
    if (type === 'IHDR') {
      width = body.readUInt32BE(0);
      height = body.readUInt32BE(4);
      assert.equal(body[8], 8, `${path}: expected 8-bit channels`);
      assert.equal(body[9], 6, `${path}: expected RGBA`);
    } else if (type === 'IDAT') {
      idat.push(body);
    }
    offset += 12 + length;
  }

  const raw = inflateSync(Buffer.concat(idat));
  const stride = width * 4;
  const pixels = Buffer.alloc(stride * height);
  for (let y = 0; y < height; y += 1) {
    assert.equal(raw[y * (stride + 1)], 0, `${path}: expected unfiltered scanlines`);
    raw.copy(pixels, y * stride, y * (stride + 1) + 1, (y + 1) * (stride + 1));
  }
  return { width, height, pixels };
}

/** Bounding box of everything more than half opaque. */
function opaqueBounds({ width, height, pixels }) {
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      if (pixels[(y * width + x) * 4 + 3] > 127) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  return { minX, minY, maxX, maxY };
}

const RES = 'android/app/src/main/res';

const LEGACY = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
const ADAPTIVE = { mdpi: 108, hdpi: 162, xhdpi: 216, xxhdpi: 324, xxxhdpi: 432 };

test('legacy launcher icons exist at every density', () => {
  for (const [density, size] of Object.entries(LEGACY)) {
    for (const name of ['ic_launcher', 'ic_launcher_round']) {
      const file = `${RES}/mipmap-${density}/${name}.png`;
      assert.ok(existsSync(file), `${file} is missing`);
      const png = readPng(file);
      assert.equal(png.width, size, `${file} should be ${size}px`);
      assert.equal(png.height, size, `${file} should be ${size}px`);
    }
  }
});

test('adaptive foregrounds exist on the 108dp canvas at every density', () => {
  for (const [density, size] of Object.entries(ADAPTIVE)) {
    const file = `${RES}/mipmap-${density}/ic_launcher_foreground.png`;
    assert.ok(existsSync(file), `${file} is missing`);
    const png = readPng(file);
    assert.equal(png.width, size, `${file} should be ${size}px`);
    assert.equal(png.height, size, `${file} should be ${size}px`);
  }
});

test('the adaptive foreground stays inside the guaranteed-visible safe zone', () => {
  // Only the central 72 of an adaptive icon's 108dp canvas always survives the
  // launcher's mask; art outside it can be cropped away on some devices.
  for (const [density, size] of Object.entries(ADAPTIVE)) {
    const file = `${RES}/mipmap-${density}/ic_launcher_foreground.png`;
    const { minX, minY, maxX, maxY } = opaqueBounds(readPng(file));
    const low = (size * 18) / 108;
    const high = (size * 90) / 108;
    assert.ok(maxX > minX, `${file} appears to be blank`);
    assert.ok(
      minX >= low && maxX <= high && minY >= low && maxY <= high,
      `${file}: art spans ${minX}-${maxX} x ${minY}-${maxY}, outside the safe zone ${low.toFixed(0)}-${high.toFixed(0)} (${density})`,
    );
  }
});

test('the adaptive foreground is drawn large enough to read', () => {
  const size = ADAPTIVE.xxxhdpi;
  const { minY, maxY } = opaqueBounds(readPng(`${RES}/mipmap-xxxhdpi/ic_launcher_foreground.png`));
  const heightDp = ((maxY - minY + 1) / size) * 108;
  assert.ok(heightDp > 40 && heightDp < 60, `glyph is ${heightDp.toFixed(1)}dp tall; expected roughly 46dp`);
});

test('the Play listing icon is a 512px square', () => {
  const png = readPng('assets/icon-512.png');
  assert.equal(png.width, 512);
  assert.equal(png.height, 512);
});

test('the web manifest icon is a 192px square', () => {
  const png = readPng('assets/icon-192.png');
  assert.equal(png.width, 192);
  assert.equal(png.height, 192);
});
